[package]
name = "atomic_utilities"
version = "0.1.0"
authors = ["Samuel Schetterer <samschet@gmail.com>"]
description = "Basic utilities for fast atomics on multiple platforms"
license = "MIT"

[dependencies]
